### ISSUE TITLE
Setting data object does not result in mapping

### ISSUE THREAD

**Issue by bretcamblempc** [Tealium/tealium-collect-adobe-launch-extension#1]
I've set the data object to "digitalData" in our config screen. This is the name of our data layer. It's not flat. The built-in direct call evaluator is not using the dataObject setting to populate payloads sent to the CDH. It does reflect the string value of the setting for dataObject, but no values within digitalData are mapped. 

I've used custom calls to 
`tealium.track('test', teal.flattenObject(digitalData)) `
to verify that it will accept a flattened object and the call was successful.

**Comment by tygavin** [comment]
I may need some more details.  If I do the following "direct" call:

`_satellite.track("direct", {hello:"direct_world", hello2: {nested: "myobj"}});`

Then I see this in the data layer:

```
...
        "turbineBuildDate": "2020-06-23T16:22:36Z",
        "turbineVersion": "26.0.2",
        "hello": "direct_world",
        "hello2.nested": "myobj",
...
```

**Comment by bretcamblempc** [comment]
We are configuring the Extension with a reference to our data layer object, digitalData. The expectation based on this configuration option is that it will collect that object at runtime. Our direct call looks like this
`_satellite.track('pageView');`
We do not pass the event meta data as a payload to parameter 2.  Would the tealium.track() call know to bring in the digitalData Object as the payload in this case? If not, I need to write a custom Action so that I can ensure that it does.

It's all wrapped up in one Action right now, initialization and .track() call. If they were broken into two Actions, I could initialize the library, then make custom use of tealium.track() in a custom Action. Happy to accept this approach, if needed. 

Plan A: pull in the provided object as the event payload.
Plan B: segregate library initialization and .track calls into two separate Actions. 

Would either of these be possible?

**Comment by bretcamblempc** [comment]
I'm also working internally to see if we can switch to an event data payload approach, like you are suggesting.

**Comment by tygavin** [comment]
Thank you for these details. It seems reasonable to add support for your "Plan A" option -- when there is no event detail then go grab the global data object automatically and use that for data layer.  I'll plan to add that logic in the next release.

This was originally built assuming an object would be explicitly passed for a direct call implementation.
_satellite.track("direct", digitalData);  // as opposed to just _satellite.track("direct");

**Comment by bretcamblempc** [comment]
Your approach is certainly more reliable, so it's a safe assumption. We have some timing issues because of the approach we are using; Sometimes digitalData is changed before our processes for an event are complete. Using a payload parameter approach is industry standard and prevents these problems, so I'm pushing for a change. I've edited our functions which call _satellite.track() to pass in the object as a parameter and things are working as intended in this Extensions current version. Thanks for the help, and I'll leave it up to you whether you want to still include this idea in future releases. Thanks!
